CREATE TABLE IF NOT EXISTS users(
id UUID PRIMARY KEY,
name VARCHAR(255),
lastname VARCHAR(255),
email VARCHAR(255) UNIQUE,
password VARCHAR(255),
role VARCHAR(255)
CHECK (role in ('ADMIN', 'USER'))
);